-- Database Performance Optimization Indexes
-- Generated by Zenith Platform Performance Optimization Agent

-- User table optimizations
CREATE INDEX IF NOT EXISTS idx_user_email ON "User" ("email");
CREATE INDEX IF NOT EXISTS idx_user_created_at ON "User" ("createdAt");
CREATE INDEX IF NOT EXISTS idx_user_updated_at ON "User" ("updatedAt");

-- Team table optimizations
CREATE INDEX IF NOT EXISTS idx_team_created_at ON "Team" ("createdAt");
CREATE INDEX IF NOT EXISTS idx_team_updated_at ON "Team" ("updatedAt");

-- Project table optimizations
CREATE INDEX IF NOT EXISTS idx_project_team_id ON "Project" ("teamId");
CREATE INDEX IF NOT EXISTS idx_project_created_at ON "Project" ("createdAt");
CREATE INDEX IF NOT EXISTS idx_project_status ON "Project" ("status");

-- Activity table optimizations
CREATE INDEX IF NOT EXISTS idx_activity_user_id ON "Activity" ("userId");
CREATE INDEX IF NOT EXISTS idx_activity_team_id ON "Activity" ("teamId");
CREATE INDEX IF NOT EXISTS idx_activity_timestamp ON "Activity" ("timestamp");
CREATE INDEX IF NOT EXISTS idx_activity_type ON "Activity" ("type");

-- Agent models optimizations
CREATE INDEX IF NOT EXISTS idx_agent_conversation_session_id ON "AgentConversation" ("sessionId");
CREATE INDEX IF NOT EXISTS idx_agent_conversation_timestamp ON "AgentConversation" ("timestamp");

-- Performance monitoring indexes
CREATE INDEX IF NOT EXISTS idx_performance_metric_timestamp ON "PerformanceMetric" ("timestamp");
CREATE INDEX IF NOT EXISTS idx_performance_metric_agent_id ON "PerformanceMetric" ("agentId");

-- Agent delegation indexes
CREATE INDEX IF NOT EXISTS idx_agent_delegation_session_id ON "AgentDelegation" ("sessionId");
CREATE INDEX IF NOT EXISTS idx_agent_delegation_timestamp ON "AgentDelegation" ("timestamp");

-- Search mastery indexes
CREATE INDEX IF NOT EXISTS idx_search_mastery_session_session_id ON "SearchMasterySession" ("sessionId");
CREATE INDEX IF NOT EXISTS idx_search_mastery_session_timestamp ON "SearchMasterySession" ("timestamp");

-- Review campaign indexes
CREATE INDEX IF NOT EXISTS idx_review_campaign_team_id ON "ReviewCampaign" ("teamId");
CREATE INDEX IF NOT EXISTS idx_review_campaign_status ON "ReviewCampaign" ("status");

-- Integration architect indexes
CREATE INDEX IF NOT EXISTS idx_integration_architect_session_session_id ON "IntegrationArchitectSession" ("sessionId");
CREATE INDEX IF NOT EXISTS idx_integration_architect_session_timestamp ON "IntegrationArchitectSession" ("timestamp");

-- Composite indexes for common queries
CREATE INDEX IF NOT EXISTS idx_project_team_status ON "Project" ("teamId", "status");
CREATE INDEX IF NOT EXISTS idx_activity_user_timestamp ON "Activity" ("userId", "timestamp");
CREATE INDEX IF NOT EXISTS idx_activity_team_timestamp ON "Activity" ("teamId", "timestamp");

-- Audit trail indexes
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON "AuditLog" ("timestamp");
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON "AuditLog" ("userId");
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON "AuditLog" ("action");

-- Analytics indexes
CREATE INDEX IF NOT EXISTS idx_ab_test_experiment_variant ON "ABTestParticipant" ("experimentId", "variant");
CREATE INDEX IF NOT EXISTS idx_analytics_event_timestamp ON "AnalyticsEvent" ("timestamp");
CREATE INDEX IF NOT EXISTS idx_analytics_event_user_id ON "AnalyticsEvent" ("userId");

-- Partnership ecosystem indexes
CREATE INDEX IF NOT EXISTS idx_partner_created_at ON "Partner" ("createdAt");
CREATE INDEX IF NOT EXISTS idx_partner_status ON "Partner" ("status");

-- CRM indexes
CREATE INDEX IF NOT EXISTS idx_crm_contact_team_id ON "CRMContact" ("teamId");
CREATE INDEX IF NOT EXISTS idx_crm_contact_status ON "CRMContact" ("status");

ANALYZE;