[build]
builder = "nixpacks"
watchPatterns = ["**/*.ts", "**/*.js", "**/*.json", "prisma/**"]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
numReplicas = 1
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[environments.staging]
name = "staging"

[environments.staging.deploy]
numReplicas = 1

[environments.staging.variables]
NODE_ENV = "staging"
RAILWAY_ENVIRONMENT = "staging"
DATABASE_POOL_MIN = "2"
DATABASE_POOL_MAX = "10"
DATABASE_CONNECTION_TIMEOUT = "10000"
DATABASE_IDLE_TIMEOUT = "30000"
DATABASE_SSL_ENABLED = "true"
BACKUP_ENABLED = "true"
DATABASE_MONITORING_ENABLED = "true"
HEALTH_CHECK_ENABLED = "true"
PRISMA_LOG_LEVEL = "info"

[environments.production]
name = "production"

[environments.production.deploy]
numReplicas = 2

[environments.production.variables]
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "production"
DATABASE_POOL_MIN = "5"
DATABASE_POOL_MAX = "20"
DATABASE_CONNECTION_TIMEOUT = "15000"
DATABASE_IDLE_TIMEOUT = "60000"
DATABASE_SSL_ENABLED = "true"
BACKUP_ENABLED = "true"
DATABASE_MONITORING_ENABLED = "true"
HEALTH_CHECK_ENABLED = "true"
PRISMA_LOG_LEVEL = "warn"